// import "./sjhs/index"
// import "./test/箭头跟随鼠标运动"
// import "./test/加速度和重力加速度"
// import "./test/边界处理"
// import "./test/边界处理_小球喷泉"
// import "./test/边界处理_箭头控制"
// import "./test/边界处理_边界反弹"
// import "./test/mouseEvent/鼠标与图像的交互"
// import "./test/advance/缓动案例_箭头"
// import "./test/advance/弹动"
// import "./test/advance/弹动_橡皮筋"
// import "./test/advance/弹动_多小球"
import "./test/advance/碰撞检测_矩形"
